### ISSUE TITLE
Action won't install...

### ISSUE THREAD

**Issue by methnen** [paulgrav/Handbrake-Automator-Action#1]
When I double click on the action and choose install it apparently attempts to install it however the action never becomes available inside of Automator.  Is this possibly a new issue?  Running latest version of OS X Lion.

**Comment by methnen** [comment]
Related to this when attempting to install, it actually says, The action "Handbrake Encode" could not be loaded because it could not be located....  

Forgot it said that.  This is on two separate machines both running the latest version of Lion.

**Comment by methnen** [comment]
OK, I think it's an OS version issues.  Seems actions for 10.6 aren't compatible with 10.7 and vice versa.  Do you have any plans to update this for OS 10.7?

**Comment by paulgrav** [comment]
Thanks.  Didn't realise anyone was using this action.  I'll have a look into it.  Can't think off the top of my head what the issue could be...

**Comment by paulgrav** [comment]
Can you try version 1.0.2 in the downloads?  It seems to work for me.

**Comment by methnen** [comment]
Hey Paul,

Thanks a lot.  Is the compiled version at the bottom upgraded?

**Comment by paulgrav** [comment]
Yeah, you'll want to download this: https://github.com/downloads/paulgrav/Handbrake-Automator-Action/HandbrakeEncode-1.0.2.zip

**Comment by methnen** [comment]
Seems to be working now.  :)  Appreciate it.  Is there any chance you might make it so that it can set the output folder?  Otherwise this is basically perfect.

**Comment by paulgrav** [comment]
How do this work? http://cl.ly/C7iw

**Comment by methnen** [comment]
Perfect, I appreciate it.
